language: scala
scala:
   - 2.11.11
   - 2.12.3
jdk:
  - openjdk7
  - openjdk8
matrix:
  fast_finish: true
  exclude:
  # not compatible versions
  - jdk: openjdk7
    scala: 2.12.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION jacoco:cover
after_success:
  - bash <(curl -s https://codecov.io/bash)